spring:
  profiles:
    default: local
application:
  title: MySpringBatchExample Project
  version: 1.0
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:~/test;MODE=LEGACY
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:h2/schema.sql
#      data-locations: classpath:h2/data.sql
  jpa:
    defer-datasource-initialization: true
  batch:
    jdbc:
      initialize-schema: always


server:
  port: 9090

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080